### ISSUE TITLE
What was your best programming moment?

### ISSUE THREAD

**Issue by sindresorhus** [zachleat/ama#3]

**Comment by zachleat** [comment]
One of my worst is documented in [A Story about Proxy Filters](https://www.zachleat.com/web/proxy-filter/)

One of my best would have to be ~2010, when the company I was working at was deciding whether to make a very substantial hardware purchase for a large number of intranet machines used to access their web sites, scattered in different field offices throughout the US.

I was tasked with performance profiling our component library to see if sufficient gains could be made to avoid the hardware purchase. They were progressive in that they’d had a centralized reusable component library used across almost all of their web properties. Of course, at that time, our browsing statistics were almost exclusively Internet Explorer 8 (the default browser installed on these company machines). Sufficient development tooling, to my knowledge, for IE8 was limited.

But I found an amazing tool called _dynaTrace AJAX Edition_. I learned more in two weeks diving into performance profiles in that tool that maybe the 4 or 5 prior combined. It’s one thing to read about Layout/Reflow, Repaints, and it’s another to see them slog the perf of a page due to some (what you thought was) innocuous JavaScript.

One of the biggest offenders and lessons learned (aside from the DataTables/Grid plugins that plague Enterprise software) was a placeholder polyfill plugin. On initialization and on focus/blur, it would toggle a `class` to change the color of the text depending on if the value of the input was empty or not (as placeholders do). But in IE8, when you toggle a `class`, it reflowed. Do this for a bunch of form fields and you have a recipe for performance disaster. Because this class was only toggling the `color` CSS property, simply switching it toggle the style directly.

Anyway, repeating that process and reprofiling a bunch of different applications yielded huge performance gains and they were able to save a ton of money by delaying that hardware purchase. Fell in love with performance profiling and learned never to underestimate the importance of great tooling.
